project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Adaptive Capacity of New York City"
  site-url: "https://musa-550-fall-2023.github.io/Adaptive-Capacity-of-New-York-City" 
  repo-url: https://github.com/Umez4w4/MUSA-550-Final_X_Wei
  repo-actions: [source]

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/) with data acquied from ACS API, NYC DEP, NYC Open Data and Rebuild by Design."
    left: "&copy; Making Room for the Water, Rebuild by Design, 2012-2024"

  sidebar:
    logo: "images/MRFTW.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://jweiresilience.com/
        text: "Personal Website"      

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Introduction
      - about.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/Adaptive Capacity and Response Interpretation.qmd
          - analysis/Infrastructure Capacity and Development Capacity.qmd
          - analysis/Housing Database and Community Adaptivity.qmd
      - href: analysis/result.qmd
        text: Conclusion
        
format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




