# Analysis

This section includes examples of technical analysis done using Jupyter notebooks.
Each sub-section highlights different types of analyses and visualizations.
In particular, it highlights that we can easily publish interactive visualizations
produced with packages such as hvPlot, altair, or Folium, without losing
any of the interactive features. 

This final project will explore the evaluation process of the Adaptive Capacity Index, featuring with web-based data visualization. This analysis is derived from research project “Making Room for the Water” (https://rebuildbydesign.org/making-room-for-the-water/), but for the purpose of a final project, the research area is changed, and fields of interest are rearranged.
	The data source will be a combination of ACS API (REQUIREMENT 1) and zonal statistics exported from ArcGIS analysis. Local and online datasets will be combined using geospatial join, and data frame operations will be used to make the database tidier (REQUIREMENT 2). Different parameters from API will be divided into several indicator sets, which act as the index layer in the decision tree. These indexes is based on panel discussion in NYC rainproof symposium. In the panel discussion, we encouraged participants to indicate barriers, goals, responsibilities, and stakeholders. After analyzing the responses, we can determine how we are assessing the adaptive capacity, and how we are developing our strategy set. World cloud will be displayed to demonstrate stakeholders’ perspective of view.
The development capacity index and the infrastructure index is processed in ArcGIS, with dataset from NYC Open Data and NYC DEP (REQUIREMENT 3). The demographic index will be evaluated based on ACS database, as different parameters will be input of TOPSIS approach, which determines the calibrated weight, then the index is generated from the process of weighed overlay. Then another level of TOPSIS calibration will combine the three indexes together, with an output of overall risk level, divided into 5 categories. For cross-reference, clustering analysis will also be performed based on the three indexes, and interactive charts will be utilized to demonstrate how the conclusion of clustering analysis may differ from a linear weighted sum of parameters (REQUIREMENT 4).
	This project is an individual project, and of all the possible requirements to satisfy, it should qualify with 4, while 2 is required.
